# Generated by Django 6.0 on 2025-12-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'ASIGNATURA',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Aulas',
                'db_table': 'AULA',
            },
        ),
        migrations.CreateModel(
            name='HoraGuardia',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'Horas de Guardia',
                'db_table': 'HORA_GUARDIA',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido1', models.CharField(max_length=45)),
                ('apellido2', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'db_table': 'PROFESOR',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_column='id_fecha')),
                ('falta_profe', models.BooleanField(default=False)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='dashboard.asignatura')),
                ('aula', models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.CASCADE, to='dashboard.aula')),
                ('hora', models.ForeignKey(db_column='id_hora', on_delete=django.db.models.deletion.CASCADE, to='dashboard.horaguardia')),
                ('profesor', models.ForeignKey(db_column='id_profesor', on_delete=django.db.models.deletion.CASCADE, to='dashboard.profesor')),
            ],
            options={
                'verbose_name_plural': 'Clases',
                'db_table': 'CLASE',
                'unique_together': {('profesor', 'hora', 'aula', 'fecha', 'asignatura')},
            },
        ),
    ]
